version: '3'
services:
  backend:
    build: ./docker/backend
    hostname: backend
    tty: true
    privileged: true
    networks:
      static-network-1:
        ipv4_address: 172.28.1.2
      static-network-2:
        ipv4_address: 192.28.1.2
      envoymesh:
        aliases:
          - backend
    expose:
      - "8001"
    ports:
      - "8001:8001"
  invoice:
    build: ./docker/invoice
    hostname: invoice
    tty: true
    privileged: true
    networks:
      static-network-1:
        ipv4_address: 172.28.1.1
    expose:
      - "5000"
    ports:
      - "5000:5000"
  opa:
    image: openpolicyagent/opa:0.24.0-envoy-5
    volumes:
    - ./docker/backend/opa/policies:/policies
    - ./docker/backend/opa/config:/config
    command:
    - run
    - --server
    - --log-level=info
    - --config-file=/config/config.yaml
    - /policies/policy.rego
    networks:
      static-network-1:
        ipv4_address: 172.28.1.3
      envoymesh:
        aliases:
          - opa
    expose:
      - "9191"
    ports:
      - "9191:9191"
networks:
  envoymesh: {}
  static-network-1:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  static-network-2:
    ipam:
      driver: default
      config:
        - subnet: 192.28.0.0/16
